/*
 * Post Service
 *
 * a post service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	"github.com/flexzuu/thesis/micro-service/rest/rating/openapi"
	cors "github.com/rs/cors/wrapper/gin"
)

func main() {
	log.Printf("Server started")

	router := openapi.NewRouter()
	router.Use(cors.Default())
	log.Fatal(router.Run(":4003"))
}
