// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user/user.proto

package user

import (
	context "context"
	fmt "fmt"
	stats "github.com/flexzuu/benchmark/micro-service/grpc/stats"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the ID
type GetUserRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a54e5b41e277c759, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

// The request message containing the ID
type CreateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a54e5b41e277c759, []int{1}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The request message containing the ID
type DeleteUserRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a54e5b41e277c759, []int{2}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type User struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a54e5b41e277c759, []int{3}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
	proto.RegisterType((*User)(nil), "user.User")
}

func init() { proto.RegisterFile("user/user/user.proto", fileDescriptor_a54e5b41e277c759) }

var fileDescriptor_a54e5b41e277c759 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0x85, 0xc2, 0x8f, 0x5f, 0x1c, 0x13, 0x12, 0x36, 0x44, 0x49, 0xbd, 0x90, 0x7a, 0xf1, 0xc2,
	0x6e, 0xa2, 0x27, 0x43, 0x4c, 0x08, 0x62, 0x08, 0xd7, 0xaa, 0x17, 0x6f, 0x6d, 0x19, 0x4a, 0x63,
	0xb7, 0x5b, 0xf7, 0x8f, 0x11, 0x3f, 0xb3, 0x1f, 0xc2, 0x74, 0x37, 0x80, 0x14, 0xbd, 0x4c, 0x66,
	0xde, 0xbc, 0xe9, 0xcb, 0x7b, 0x5d, 0xe8, 0x1b, 0x85, 0x92, 0xed, 0x0a, 0x2d, 0xa5, 0xd0, 0x82,
	0xb4, 0xab, 0xde, 0xef, 0x29, 0x1d, 0x69, 0xc5, 0x6c, 0x75, 0x0b, 0xff, 0x22, 0x15, 0x22, 0xcd,
	0x91, 0xd9, 0x29, 0x36, 0x2b, 0x86, 0xbc, 0xd4, 0x1b, 0xb7, 0x0c, 0x86, 0xd0, 0x9d, 0xa3, 0x7e,
	0x56, 0x28, 0x43, 0x7c, 0x33, 0xa8, 0x34, 0xe9, 0x82, 0xb7, 0x98, 0x0d, 0x9a, 0xc3, 0xe6, 0x55,
	0x2b, 0xf4, 0x16, 0xb3, 0xe0, 0x0e, 0x7a, 0xf7, 0x12, 0x23, 0x8d, 0x3f, 0x49, 0x7d, 0xf8, 0x87,
	0x3c, 0xca, 0x72, 0xcb, 0x3b, 0x09, 0xdd, 0x40, 0x08, 0xb4, 0x8b, 0x88, 0xe3, 0xc0, 0xb3, 0xa0,
	0xed, 0x83, 0x4b, 0xe8, 0xcd, 0x30, 0xc7, 0xc3, 0xf3, 0xba, 0xc6, 0x04, 0xda, 0xd5, 0xba, 0x8e,
	0xef, 0x65, 0xbc, 0xdf, 0x64, 0x5a, 0x7b, 0x99, 0xeb, 0xaf, 0x26, 0x9c, 0x56, 0x9f, 0x78, 0x44,
	0xf9, 0x9e, 0x25, 0x48, 0x46, 0xf0, 0x7f, 0x8e, 0x7a, 0xba, 0x59, 0x2c, 0x49, 0x9f, 0xda, 0x94,
	0x0e, 0x6d, 0xfa, 0xe0, 0xd0, 0x0a, 0x0a, 0x1a, 0x84, 0x41, 0xc7, 0x99, 0x24, 0xe7, 0x0e, 0x3f,
	0xb2, 0x5c, 0x3b, 0x18, 0x43, 0xc7, 0xd9, 0xda, 0x1e, 0x1c, 0x99, 0xf4, 0xcf, 0xa8, 0x0b, 0x9e,
	0x6e, 0x83, 0xa7, 0x0f, 0x55, 0xf0, 0x41, 0x83, 0x4c, 0x00, 0x42, 0x61, 0x8a, 0xe5, 0x93, 0xcc,
	0x4a, 0x45, 0xfe, 0xe0, 0xf9, 0x03, 0xea, 0xfe, 0xe2, 0x8e, 0x1a, 0xa2, 0x2a, 0x45, 0xa1, 0x30,
	0x68, 0x4c, 0xc7, 0x2f, 0xb7, 0x69, 0xa6, 0xd7, 0x26, 0xa6, 0x89, 0xe0, 0x6c, 0x95, 0xe3, 0xc7,
	0xa7, 0x31, 0x2c, 0xc6, 0x22, 0x59, 0xf3, 0x48, 0xbe, 0x32, 0x9e, 0x25, 0x52, 0x8c, 0x94, 0x0b,
	0x83, 0xa5, 0xb2, 0x4c, 0xf6, 0xef, 0x25, 0xee, 0x58, 0xa1, 0x9b, 0xef, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x53, 0x77, 0x48, 0x1d, 0x48, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	// Get a single User by ID
	GetById(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	// Create a single User validates if the passed AuthorId is valid
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	// Delete a single User by ID
	Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	RoundTrips(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*stats.RoundTripResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetById(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.UserService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/user.UserService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RoundTrips(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*stats.RoundTripResponse, error) {
	out := new(stats.RoundTripResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/RoundTrips", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	// Get a single User by ID
	GetById(context.Context, *GetUserRequest) (*User, error)
	// Create a single User validates if the passed AuthorId is valid
	Create(context.Context, *CreateUserRequest) (*User, error)
	// Delete a single User by ID
	Delete(context.Context, *DeleteUserRequest) (*empty.Empty, error)
	RoundTrips(context.Context, *empty.Empty) (*stats.RoundTripResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetById(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RoundTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RoundTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/RoundTrips",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RoundTrips(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _UserService_GetById_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserService_Delete_Handler,
		},
		{
			MethodName: "RoundTrips",
			Handler:    _UserService_RoundTrips_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user/user.proto",
}
