/*
 * Post Service
 *
 * a post service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PostListModel - a list of posts
type PostListModel struct {
	Posts []PostModel `json:"posts"`
}
