/*
 * Post Service
 *
 * a post service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CreatePostModel - create post body
type CreatePostModel struct {
	AuthorId int64 `json:"authorId"`

	Headline string `json:"headline,omitempty"`

	// content as markdown
	Content string `json:"content,omitempty"`
}
