// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post/post/post.proto

package post

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the ID
type GetPostRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_924b6a3e85d40a14, []int{0}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

//
type ListPostsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsRequest) Reset()         { *m = ListPostsRequest{} }
func (m *ListPostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPostsRequest) ProtoMessage()    {}
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_924b6a3e85d40a14, []int{1}
}

func (m *ListPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsRequest.Unmarshal(m, b)
}
func (m *ListPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsRequest.Marshal(b, m, deterministic)
}
func (m *ListPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsRequest.Merge(m, src)
}
func (m *ListPostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPostsRequest.Size(m)
}
func (m *ListPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsRequest proto.InternalMessageInfo

//
type ListPostsOfAuthorRequest struct {
	AuthorID             int64    `protobuf:"varint,1,opt,name=AuthorID,proto3" json:"AuthorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsOfAuthorRequest) Reset()         { *m = ListPostsOfAuthorRequest{} }
func (m *ListPostsOfAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*ListPostsOfAuthorRequest) ProtoMessage()    {}
func (*ListPostsOfAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_924b6a3e85d40a14, []int{2}
}

func (m *ListPostsOfAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsOfAuthorRequest.Unmarshal(m, b)
}
func (m *ListPostsOfAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsOfAuthorRequest.Marshal(b, m, deterministic)
}
func (m *ListPostsOfAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsOfAuthorRequest.Merge(m, src)
}
func (m *ListPostsOfAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_ListPostsOfAuthorRequest.Size(m)
}
func (m *ListPostsOfAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsOfAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsOfAuthorRequest proto.InternalMessageInfo

func (m *ListPostsOfAuthorRequest) GetAuthorID() int64 {
	if m != nil {
		return m.AuthorID
	}
	return 0
}

// The request message containing the ID
type CreatePostRequest struct {
	AuthorID             int64    `protobuf:"varint,1,opt,name=authorID,proto3" json:"authorID,omitempty"`
	Headline             string   `protobuf:"bytes,2,opt,name=headline,proto3" json:"headline,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_924b6a3e85d40a14, []int{3}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetAuthorID() int64 {
	if m != nil {
		return m.AuthorID
	}
	return 0
}

func (m *CreatePostRequest) GetHeadline() string {
	if m != nil {
		return m.Headline
	}
	return ""
}

func (m *CreatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// The request message containing the ID
type DeletePostRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostRequest) Reset()         { *m = DeletePostRequest{} }
func (m *DeletePostRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePostRequest) ProtoMessage()    {}
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_924b6a3e85d40a14, []int{4}
}

func (m *DeletePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostRequest.Unmarshal(m, b)
}
func (m *DeletePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostRequest.Marshal(b, m, deterministic)
}
func (m *DeletePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostRequest.Merge(m, src)
}
func (m *DeletePostRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePostRequest.Size(m)
}
func (m *DeletePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostRequest proto.InternalMessageInfo

func (m *DeletePostRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

// A list of Posts
type ListPostsResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsResponse) Reset()         { *m = ListPostsResponse{} }
func (m *ListPostsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostsResponse) ProtoMessage()    {}
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_924b6a3e85d40a14, []int{5}
}

func (m *ListPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsResponse.Unmarshal(m, b)
}
func (m *ListPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsResponse.Marshal(b, m, deterministic)
}
func (m *ListPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsResponse.Merge(m, src)
}
func (m *ListPostsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostsResponse.Size(m)
}
func (m *ListPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsResponse proto.InternalMessageInfo

func (m *ListPostsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type Post struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	AuthorID             int64    `protobuf:"varint,2,opt,name=authorID,proto3" json:"authorID,omitempty"`
	Headline             string   `protobuf:"bytes,3,opt,name=headline,proto3" json:"headline,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_924b6a3e85d40a14, []int{6}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Post) GetAuthorID() int64 {
	if m != nil {
		return m.AuthorID
	}
	return 0
}

func (m *Post) GetHeadline() string {
	if m != nil {
		return m.Headline
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPostRequest)(nil), "post.GetPostRequest")
	proto.RegisterType((*ListPostsRequest)(nil), "post.ListPostsRequest")
	proto.RegisterType((*ListPostsOfAuthorRequest)(nil), "post.ListPostsOfAuthorRequest")
	proto.RegisterType((*CreatePostRequest)(nil), "post.CreatePostRequest")
	proto.RegisterType((*DeletePostRequest)(nil), "post.DeletePostRequest")
	proto.RegisterType((*ListPostsResponse)(nil), "post.ListPostsResponse")
	proto.RegisterType((*Post)(nil), "post.Post")
}

func init() { proto.RegisterFile("post/post/post.proto", fileDescriptor_924b6a3e85d40a14) }

var fileDescriptor_924b6a3e85d40a14 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x6d, 0x3e, 0xec, 0xae, 0x77, 0x65, 0xb1, 0xc3, 0xb2, 0x86, 0x08, 0x12, 0xc6, 0x97, 0xbe,
	0x6c, 0x06, 0x56, 0x14, 0x4a, 0x9f, 0xac, 0x95, 0x12, 0x10, 0x94, 0xfa, 0xe6, 0x5b, 0x92, 0xde,
	0x26, 0xc1, 0x24, 0x13, 0x33, 0x13, 0xb1, 0xfe, 0x2a, 0x7f, 0xa2, 0x4c, 0xa6, 0x89, 0x4d, 0x8a,
	0x7d, 0x09, 0xb9, 0xe7, 0x7e, 0x9e, 0x7b, 0xee, 0xc0, 0x5d, 0xc5, 0x85, 0x64, 0xfd, 0xc7, 0xaf,
	0x6a, 0x2e, 0x39, 0xb1, 0xd5, 0xbf, 0xfb, 0x32, 0xe1, 0x3c, 0xc9, 0x91, 0xb5, 0x58, 0xd4, 0xec,
	0x19, 0x16, 0x95, 0x3c, 0xe8, 0x10, 0xea, 0xc1, 0xed, 0x06, 0xe5, 0x17, 0x2e, 0xe4, 0x16, 0x7f,
	0x34, 0x28, 0x24, 0xb9, 0x05, 0x33, 0x58, 0x3b, 0x86, 0x67, 0xcc, 0xad, 0xad, 0x19, 0xac, 0x29,
	0x81, 0xe7, 0x9f, 0x32, 0xd1, 0x86, 0x88, 0x63, 0x0c, 0x7d, 0x07, 0x4e, 0x8f, 0x7d, 0xde, 0xbf,
	0x6f, 0x64, 0xca, 0xeb, 0x2e, 0xdf, 0x85, 0x6b, 0x0d, 0xf4, 0x55, 0x7a, 0x9b, 0x22, 0xcc, 0x3e,
	0xd4, 0x18, 0x4a, 0x3c, 0x6d, 0xe8, 0xc2, 0x75, 0x38, 0x4a, 0xe8, 0x6c, 0xe5, 0x4b, 0x31, 0xdc,
	0xe5, 0x59, 0x89, 0x8e, 0xe9, 0x19, 0xf3, 0xa7, 0xdb, 0xde, 0x26, 0x0e, 0x5c, 0xc5, 0xbc, 0x94,
	0x58, 0x4a, 0xc7, 0x6a, 0x5d, 0x9d, 0x49, 0x5f, 0xc3, 0x6c, 0x8d, 0x39, 0x0e, 0xdb, 0x8c, 0x79,
	0xbd, 0x85, 0xd9, 0x09, 0x2f, 0x51, 0xf1, 0x52, 0x20, 0xf1, 0xe0, 0x89, 0xda, 0x99, 0x70, 0x0c,
	0xcf, 0x9a, 0xdf, 0x3c, 0x82, 0xdf, 0x6e, 0xb3, 0x2d, 0xa3, 0x1d, 0x34, 0x05, 0x5b, 0x99, 0xe3,
	0x72, 0x03, 0x16, 0xe6, 0x05, 0x16, 0xd6, 0xff, 0x59, 0xd8, 0x03, 0x16, 0x8f, 0x7f, 0x4c, 0xb8,
	0x51, 0xad, 0xbe, 0x62, 0xfd, 0x33, 0x8b, 0x91, 0x3c, 0xc0, 0xd5, 0x06, 0xe5, 0xea, 0x10, 0xec,
	0xc8, 0x9d, 0x9e, 0x6b, 0xa8, 0x9c, 0x7b, 0x32, 0x2d, 0x9d, 0x90, 0x05, 0xd8, 0x8a, 0x1f, 0xb9,
	0xd7, 0xe8, 0x58, 0x43, 0xf7, 0xc5, 0x19, 0xae, 0x77, 0x40, 0x27, 0x24, 0x80, 0x67, 0x0a, 0xee,
	0x94, 0x25, 0xaf, 0x46, 0xa1, 0x23, 0xc9, 0x2f, 0x95, 0x62, 0x30, 0xd5, 0x8a, 0x93, 0x63, 0xd0,
	0x99, 0xfe, 0xa3, 0xb1, 0x97, 0x30, 0xd5, 0xda, 0x75, 0x09, 0x67, 0x4a, 0xba, 0xf7, 0xbe, 0xbe,
	0x68, 0xbf, 0xbb, 0x68, 0xff, 0xa3, 0xba, 0x68, 0x3a, 0x59, 0x2d, 0xbf, 0x2d, 0x92, 0x4c, 0xa6,
	0x4d, 0xe4, 0xc7, 0xbc, 0x60, 0xfb, 0x1c, 0x7f, 0xfd, 0x6e, 0x1a, 0x16, 0x61, 0x19, 0xa7, 0x45,
	0x58, 0x7f, 0x67, 0x45, 0x16, 0xd7, 0xfc, 0x41, 0xe8, 0x85, 0xb2, 0xa4, 0xae, 0xe2, 0x7f, 0x6f,
	0x26, 0x9a, 0xb6, 0xe5, 0xde, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x4e, 0xaf, 0xfe, 0x4c,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	// Get a single Post by ID
	GetById(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error)
	List(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
	ListOfAuthor(ctx context.Context, in *ListPostsOfAuthorRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
	// Create a single Post validates if the passed AuthorId is valid
	Create(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*Post, error)
	// Delete a single Post by ID
	Delete(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) GetById(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/post.PostService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) List(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListOfAuthor(ctx context.Context, in *ListPostsOfAuthorRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, "/post.PostService/ListOfAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Create(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/post.PostService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) Delete(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/post.PostService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	// Get a single Post by ID
	GetById(context.Context, *GetPostRequest) (*Post, error)
	List(context.Context, *ListPostsRequest) (*ListPostsResponse, error)
	ListOfAuthor(context.Context, *ListPostsOfAuthorRequest) (*ListPostsResponse, error)
	// Create a single Post validates if the passed AuthorId is valid
	Create(context.Context, *CreatePostRequest) (*Post, error)
	// Delete a single Post by ID
	Delete(context.Context, *DeletePostRequest) (*empty.Empty, error)
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetById(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).List(ctx, req.(*ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListOfAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsOfAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListOfAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/ListOfAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListOfAuthor(ctx, req.(*ListPostsOfAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Create(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post.PostService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).Delete(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "post.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _PostService_GetById_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PostService_List_Handler,
		},
		{
			MethodName: "ListOfAuthor",
			Handler:    _PostService_ListOfAuthor_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PostService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PostService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post/post/post.proto",
}
