/*
 * Facade Service
 *
 * a facade service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	post "github.com/flexzuu/thesis/example/openapi/post/openapi"
	user "github.com/flexzuu/thesis/example/openapi/user/openapi"
)

// PostDetailModel - Post with more info included
type PostDetailModel struct {
	Post post.PostModel `json:"post"`

	Author user.UserModel `json:"author"`

	AvgRating float64 `json:"avgRating"`
}
