/*
 * Rating Service
 *
 * a rating service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// a list of ratings
type RatingListModel struct {
	Ratings []RatingModel `json:"ratings,omitempty"`
}
