/*
 * Post Service
 *
 * a post service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// create post body
type CreatePostModel struct {
	AuthorId int64 `json:"authorId,omitempty"`
	Headline string `json:"headline,omitempty"`
	// content as markdown
	Content string `json:"content,omitempty"`
}
