/*
 * User Service
 *
 * a user service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// CreateUserModel - create user body
type CreateUserModel struct {

	Email string `json:"email,omitempty"`

	Name string `json:"name,omitempty"`
}
