// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package user

type UserCreateInput struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type UserDeleteInput struct {
	ID string `json:"id"`
}

type UserDeletePayload struct {
	DeletedUserID string `json:"deletedUserId"`
}
