// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package rating

type RatingCreateInput struct {
	PostID string `json:"postId"`
	Rating int    `json:"rating"`
}

type RatingDeleteInput struct {
	ID string `json:"id"`
}

type RatingDeletePayload struct {
	DeletedRatingID string `json:"deletedRatingId"`
}
