/*
 * Facade Service
 *
 * a facade service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// A User
type UserModel struct {
	Id int64 `json:"id,omitempty"`
	Email string `json:"email,omitempty"`
	Name string `json:"name,omitempty"`
}
