/*
 * Facade Service
 *
 * a facade service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Post with more info included
type PostDetailModel struct {
	Post PostModel `json:"post,omitempty"`
	Author UserModel `json:"author,omitempty"`
	AvgRating float64 `json:"avgRating,omitempty"`
}
