/*
 * Facade Service
 *
 * a facade service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Author with more info included
type AuthorDetailModel struct {
	Author UserModel `json:"author,omitempty"`
	Posts PostListModel `json:"posts,omitempty"`
	AvgRating float64 `json:"avgRating,omitempty"`
}
