/*
 * Facade Service
 *
 * a facade service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AuthorDetailModel - Author with more info included
type AuthorDetailModel struct {
	Author UserModel `json:"author"`

	Posts []PostModel `json:"posts"`

	AvgRating float64 `json:"avgRating"`
}
