/*
 * Facade Service
 *
 * a facade service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PostDetailModel - Post with more info included
type PostDetailModel struct {
	Post PostModel `json:"post"`

	Author UserModel `json:"author"`

	AvgRating float64 `json:"avgRating"`
}
