/*
 * User Service
 *
 * a user service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	"github.com/flexzuu/benchmark/micro-service/rest/user/openapi"
)

func main() {
	log.Printf("Server started")

	router := openapi.NewRouter()

	log.Fatal(router.Run(":8080"))
}
