// Code generated by protoc-gen-go. DO NOT EDIT.
// source: facade/facade/facade.proto

package facade

import (
	context "context"
	fmt "fmt"
	post "github.com/flexzuu/benchmark/micro-service/grpc/post/post"
	stats "github.com/flexzuu/benchmark/micro-service/grpc/stats"
	user "github.com/flexzuu/benchmark/micro-service/grpc/user/user"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the ID
type ListPostsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsRequest) Reset()         { *m = ListPostsRequest{} }
func (m *ListPostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPostsRequest) ProtoMessage()    {}
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70470a953dd5b88d, []int{0}
}

func (m *ListPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsRequest.Unmarshal(m, b)
}
func (m *ListPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsRequest.Marshal(b, m, deterministic)
}
func (m *ListPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsRequest.Merge(m, src)
}
func (m *ListPostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPostsRequest.Size(m)
}
func (m *ListPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsRequest proto.InternalMessageInfo

//
type ListPostsResponse struct {
	Posts                []*post.Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListPostsResponse) Reset()         { *m = ListPostsResponse{} }
func (m *ListPostsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostsResponse) ProtoMessage()    {}
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70470a953dd5b88d, []int{1}
}

func (m *ListPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsResponse.Unmarshal(m, b)
}
func (m *ListPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsResponse.Marshal(b, m, deterministic)
}
func (m *ListPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsResponse.Merge(m, src)
}
func (m *ListPostsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostsResponse.Size(m)
}
func (m *ListPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsResponse proto.InternalMessageInfo

func (m *ListPostsResponse) GetPosts() []*post.Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

// The request message containing the ID
type PostDetailRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostDetailRequest) Reset()         { *m = PostDetailRequest{} }
func (m *PostDetailRequest) String() string { return proto.CompactTextString(m) }
func (*PostDetailRequest) ProtoMessage()    {}
func (*PostDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70470a953dd5b88d, []int{2}
}

func (m *PostDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostDetailRequest.Unmarshal(m, b)
}
func (m *PostDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostDetailRequest.Marshal(b, m, deterministic)
}
func (m *PostDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostDetailRequest.Merge(m, src)
}
func (m *PostDetailRequest) XXX_Size() int {
	return xxx_messageInfo_PostDetailRequest.Size(m)
}
func (m *PostDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostDetailRequest proto.InternalMessageInfo

func (m *PostDetailRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

//
type PostDetailResponse struct {
	Post                 *post.Post `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Author               *user.User `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	AvgRating            float64    `protobuf:"fixed64,3,opt,name=avgRating,proto3" json:"avgRating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PostDetailResponse) Reset()         { *m = PostDetailResponse{} }
func (m *PostDetailResponse) String() string { return proto.CompactTextString(m) }
func (*PostDetailResponse) ProtoMessage()    {}
func (*PostDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70470a953dd5b88d, []int{3}
}

func (m *PostDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostDetailResponse.Unmarshal(m, b)
}
func (m *PostDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostDetailResponse.Marshal(b, m, deterministic)
}
func (m *PostDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostDetailResponse.Merge(m, src)
}
func (m *PostDetailResponse) XXX_Size() int {
	return xxx_messageInfo_PostDetailResponse.Size(m)
}
func (m *PostDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostDetailResponse proto.InternalMessageInfo

func (m *PostDetailResponse) GetPost() *post.Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *PostDetailResponse) GetAuthor() *user.User {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *PostDetailResponse) GetAvgRating() float64 {
	if m != nil {
		return m.AvgRating
	}
	return 0
}

// The request message containing the ID
type AuthorDetailRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorDetailRequest) Reset()         { *m = AuthorDetailRequest{} }
func (m *AuthorDetailRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorDetailRequest) ProtoMessage()    {}
func (*AuthorDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70470a953dd5b88d, []int{4}
}

func (m *AuthorDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorDetailRequest.Unmarshal(m, b)
}
func (m *AuthorDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorDetailRequest.Marshal(b, m, deterministic)
}
func (m *AuthorDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorDetailRequest.Merge(m, src)
}
func (m *AuthorDetailRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorDetailRequest.Size(m)
}
func (m *AuthorDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorDetailRequest proto.InternalMessageInfo

func (m *AuthorDetailRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

//
type AuthorDetailResponse struct {
	Author               *user.User   `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Posts                []*post.Post `protobuf:"bytes,2,rep,name=posts,proto3" json:"posts,omitempty"`
	AvgRating            float64      `protobuf:"fixed64,3,opt,name=avgRating,proto3" json:"avgRating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AuthorDetailResponse) Reset()         { *m = AuthorDetailResponse{} }
func (m *AuthorDetailResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorDetailResponse) ProtoMessage()    {}
func (*AuthorDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70470a953dd5b88d, []int{5}
}

func (m *AuthorDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorDetailResponse.Unmarshal(m, b)
}
func (m *AuthorDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorDetailResponse.Marshal(b, m, deterministic)
}
func (m *AuthorDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorDetailResponse.Merge(m, src)
}
func (m *AuthorDetailResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorDetailResponse.Size(m)
}
func (m *AuthorDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorDetailResponse proto.InternalMessageInfo

func (m *AuthorDetailResponse) GetAuthor() *user.User {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *AuthorDetailResponse) GetPosts() []*post.Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *AuthorDetailResponse) GetAvgRating() float64 {
	if m != nil {
		return m.AvgRating
	}
	return 0
}

func init() {
	proto.RegisterType((*ListPostsRequest)(nil), "facade.ListPostsRequest")
	proto.RegisterType((*ListPostsResponse)(nil), "facade.ListPostsResponse")
	proto.RegisterType((*PostDetailRequest)(nil), "facade.PostDetailRequest")
	proto.RegisterType((*PostDetailResponse)(nil), "facade.PostDetailResponse")
	proto.RegisterType((*AuthorDetailRequest)(nil), "facade.AuthorDetailRequest")
	proto.RegisterType((*AuthorDetailResponse)(nil), "facade.AuthorDetailResponse")
}

func init() { proto.RegisterFile("facade/facade/facade.proto", fileDescriptor_70470a953dd5b88d) }

var fileDescriptor_70470a953dd5b88d = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x35, 0xa9, 0x16, 0xf6, 0xfa, 0x81, 0x1d, 0x8b, 0xc4, 0xd9, 0x45, 0x4a, 0x44, 0xe8, 0x8b,
	0x33, 0xb0, 0xe2, 0xa3, 0xa8, 0x4b, 0x57, 0x58, 0xf4, 0x41, 0xa2, 0xbe, 0xf8, 0x36, 0xc9, 0x4e,
	0xd3, 0x60, 0x93, 0x89, 0xf3, 0x51, 0x74, 0xff, 0x91, 0xff, 0x52, 0x32, 0x33, 0x3b, 0x69, 0xdc,
	0x6c, 0x5f, 0x6e, 0xb9, 0xf7, 0x1c, 0xce, 0x9c, 0x9e, 0x7b, 0x03, 0x78, 0xcd, 0x0a, 0x76, 0xc9,
	0xe9, 0xe0, 0x87, 0xb4, 0x52, 0x68, 0x81, 0xa6, 0xae, 0xc3, 0xf3, 0x56, 0x28, 0x4d, 0x43, 0x71,
	0x28, 0x9e, 0x1b, 0xc5, 0x25, 0x0d, 0xc5, 0x4f, 0x67, 0x4a, 0x33, 0xad, 0xa8, 0xad, 0x7e, 0x74,
	0x5c, 0x0a, 0x51, 0x6e, 0x39, 0xb5, 0x5d, 0x6e, 0xd6, 0x94, 0xd7, 0xad, 0xfe, 0xe3, 0xc0, 0x14,
	0xc1, 0xe3, 0xcf, 0x95, 0xd2, 0x5f, 0x84, 0xd2, 0x2a, 0xe3, 0xbf, 0x0c, 0x57, 0x3a, 0x7d, 0x03,
	0xb3, 0xbd, 0x99, 0x6a, 0x45, 0xa3, 0x38, 0x5a, 0xc0, 0xbd, 0xee, 0x71, 0x95, 0x44, 0x8b, 0xc9,
	0xf2, 0xfe, 0x29, 0x10, 0x6b, 0xa5, 0xe3, 0x64, 0x0e, 0x48, 0x5f, 0xc0, 0xac, 0x6b, 0x57, 0x5c,
	0xb3, 0x6a, 0xeb, 0xb5, 0xd0, 0x23, 0x88, 0x2f, 0x56, 0x49, 0xb4, 0x88, 0x96, 0x93, 0x2c, 0xbe,
	0x58, 0xa5, 0x3b, 0x40, 0xfb, 0x24, 0x2f, 0xfe, 0x1c, 0xee, 0x76, 0x1a, 0x96, 0x37, 0xd4, 0xb6,
	0x73, 0x94, 0xc2, 0x94, 0x19, 0xbd, 0x11, 0x32, 0x89, 0x3d, 0xc3, 0xfe, 0xe5, 0xef, 0x8a, 0xcb,
	0xcc, 0x23, 0xe8, 0x04, 0x8e, 0xd8, 0xae, 0xcc, 0x98, 0xae, 0x9a, 0x32, 0x99, 0x2c, 0xa2, 0x65,
	0x94, 0xf5, 0x83, 0xf4, 0x25, 0x3c, 0xf9, 0x60, 0x79, 0x87, 0xed, 0x5d, 0xc1, 0x7c, 0x48, 0xf3,
	0x06, 0x7b, 0x03, 0xd1, 0xad, 0x06, 0x42, 0x42, 0xf1, 0x2d, 0x09, 0x1d, 0xb6, 0x78, 0xfa, 0x37,
	0x86, 0x87, 0x1f, 0xed, 0xc6, 0xbf, 0x72, 0xb9, 0xab, 0x0a, 0x8e, 0xce, 0xe0, 0x28, 0x2c, 0x02,
	0x25, 0xc4, 0x1f, 0xc7, 0xff, 0xfb, 0xc2, 0xcf, 0x46, 0x10, 0xe7, 0x3b, 0xbd, 0x83, 0xce, 0x01,
	0xfa, 0xc0, 0x51, 0xa0, 0xde, 0xd8, 0x14, 0xc6, 0x63, 0x50, 0x90, 0xf9, 0x04, 0x0f, 0xf6, 0x83,
	0x41, 0xc7, 0xd7, 0xec, 0x91, 0x54, 0xf1, 0xc9, 0x38, 0x18, 0xc4, 0xde, 0x03, 0x64, 0xc2, 0x34,
	0x97, 0xdf, 0x64, 0xd5, 0x2a, 0xf4, 0x94, 0xb8, 0x03, 0x25, 0xd7, 0x07, 0x4a, 0xce, 0xbb, 0x03,
	0xc5, 0x09, 0x71, 0x57, 0x1c, 0xa8, 0xbd, 0xc2, 0xd9, 0xbb, 0x1f, 0x6f, 0xcb, 0x4a, 0x6f, 0x4c,
	0x4e, 0x0a, 0x51, 0xd3, 0xf5, 0x96, 0xff, 0xbe, 0x32, 0x86, 0xe6, 0xbc, 0x29, 0x36, 0x35, 0x93,
	0x3f, 0x69, 0x5d, 0x15, 0x52, 0xbc, 0x52, 0x2e, 0x47, 0x5a, 0xca, 0xb6, 0x18, 0x7e, 0x61, 0xf9,
	0xd4, 0x3e, 0xf6, 0xfa, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x0e, 0x21, 0x53, 0x80, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FacadeServiceClient is the client API for FacadeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FacadeServiceClient interface {
	ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
	PostDetail(ctx context.Context, in *PostDetailRequest, opts ...grpc.CallOption) (*PostDetailResponse, error)
	AuthorDetail(ctx context.Context, in *AuthorDetailRequest, opts ...grpc.CallOption) (*AuthorDetailResponse, error)
	RoundTrips(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*stats.RoundTripResponse, error)
}

type facadeServiceClient struct {
	cc *grpc.ClientConn
}

func NewFacadeServiceClient(cc *grpc.ClientConn) FacadeServiceClient {
	return &facadeServiceClient{cc}
}

func (c *facadeServiceClient) ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, "/facade.FacadeService/ListPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) PostDetail(ctx context.Context, in *PostDetailRequest, opts ...grpc.CallOption) (*PostDetailResponse, error) {
	out := new(PostDetailResponse)
	err := c.cc.Invoke(ctx, "/facade.FacadeService/PostDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) AuthorDetail(ctx context.Context, in *AuthorDetailRequest, opts ...grpc.CallOption) (*AuthorDetailResponse, error) {
	out := new(AuthorDetailResponse)
	err := c.cc.Invoke(ctx, "/facade.FacadeService/AuthorDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) RoundTrips(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*stats.RoundTripResponse, error) {
	out := new(stats.RoundTripResponse)
	err := c.cc.Invoke(ctx, "/facade.FacadeService/RoundTrips", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FacadeServiceServer is the server API for FacadeService service.
type FacadeServiceServer interface {
	ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error)
	PostDetail(context.Context, *PostDetailRequest) (*PostDetailResponse, error)
	AuthorDetail(context.Context, *AuthorDetailRequest) (*AuthorDetailResponse, error)
	RoundTrips(context.Context, *empty.Empty) (*stats.RoundTripResponse, error)
}

func RegisterFacadeServiceServer(s *grpc.Server, srv FacadeServiceServer) {
	s.RegisterService(&_FacadeService_serviceDesc, srv)
}

func _FacadeService_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/facade.FacadeService/ListPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).ListPosts(ctx, req.(*ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_PostDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).PostDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/facade.FacadeService/PostDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).PostDetail(ctx, req.(*PostDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_AuthorDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).AuthorDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/facade.FacadeService/AuthorDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).AuthorDetail(ctx, req.(*AuthorDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_RoundTrips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).RoundTrips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/facade.FacadeService/RoundTrips",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).RoundTrips(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _FacadeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "facade.FacadeService",
	HandlerType: (*FacadeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPosts",
			Handler:    _FacadeService_ListPosts_Handler,
		},
		{
			MethodName: "PostDetail",
			Handler:    _FacadeService_PostDetail_Handler,
		},
		{
			MethodName: "AuthorDetail",
			Handler:    _FacadeService_AuthorDetail_Handler,
		},
		{
			MethodName: "RoundTrips",
			Handler:    _FacadeService_RoundTrips_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "facade/facade/facade.proto",
}
